CapaPresentacionAdmin/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CapaEntidad;
using CapaNegocio;

namespace CapaPresentacionAdmin.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Usuarios()
        {
           

            return View();
        }

        [HttpGet]
        public JsonResult ListarUsuarios()
        {
          List<Usuario> oLista = new List<Usuario>();

            oLista = new CN_Usuarios().Listar();

            return Json(new {data = oLista },JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarUsuarios(Usuario objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdUsuario == 0)
            {
                resultado = new CN_Usuarios().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Usuarios().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje= mensaje}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarUsuario(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Usuarios().Eliminar(id, out mensaje);
            
            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

    }
}

CapaPresentacionAdmin/Controllers/MantenedorController.cs
using CapaEntidad;
using CapaNegocio;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CapaPresentacionAdmin.Controllers
{
    public class MantenedorController : Controller
    {
        // GET: Mantenedor
        public ActionResult Categoria()
        {
            return View();
        }
        public ActionResult Marcas()
        {
            return View();
        }
        public ActionResult Productos()
        {
            return View();
        }
        //+++++++++++++++++++++++++CATEGORIA++++++++++++++++++++
        #region CATEGORIA
        [HttpGet]
        public JsonResult ListarCategorias()
        {
            List<Categoria> oLista = new List<Categoria>();
            oLista = new CN_Categoria().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarCategoria(Categoria objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdCategoria == 0)
            {
                resultado = new CN_Categoria().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Categoria().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarCategoria(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Categoria().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }

        #endregion CATEGORIA


        //++++++++++++++++MARCA+++++++++++++++++++++
        #region MARCA
        [HttpGet]
        public JsonResult ListarMarca()
        {
            List<Marca> oLista = new List<Marca>();
            oLista = new CN_Marca().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarca(Marca objeto)
        {
            object resultado;
            string mensaje = string.Empty;
            if (objeto.IdMarca == 0)
            {
                resultado = new CN_Marca().Registrar(objeto, out mensaje);
            }
            else
            {
                resultado = new CN_Marca().Editar(objeto, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarca(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Marca().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion MARCA



        //++++++++++++++++PRODUCTO+++++++++++++++++++++
        #region Producto

        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Producto> oLista = new List<Producto>();
            oLista = new CN_Producto().Listar();
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GuardarProducto(string objeto, HttpPostedFileBase archivoImagen )
        {
            object resultado;
            string mensaje = string.Empty;
            bool operacion_exitosa = true;
            bool guardar_imagen_exito = true;


            Producto oProducto = new Producto();
            oProducto = JsonConvert.DeserializeObject<Producto>(objeto);

            decimal precio;

            if (Decimal.TryParse(oProducto.PrecioTexto, NumberStyles.AllowDecimalPoint, new CultureInfo("es-HN"), out precio))
            {
                oProducto.Precio = precio;
            }
            else
            {
                return Json(new { operacion_exitosa = false, mensaje = "El formato debe ser ##.##" }, JsonRequestBehavior.AllowGet);
            }


            if (oProducto.IdProducto == 0)
            {
                int idProductoGenerado = new CN_Producto().Registrar(oProducto, out mensaje);

                if (idProductoGenerado != 0)
                {
                    oProducto.IdProducto = idProductoGenerado;
                }
                else
                {
                    operacion_exitosa = false;
                }


            }
            else
            {
                operacion_exitosa = new CN_Producto().Editar(oProducto, out mensaje);
            }

            if (operacion_exitosa)
            {
                if (archivoImagen !=null)
                {
                    string ruta_Guardar = ConfigurationManager.AppSettings["ServidorFotos"];

                    string extension = Path.GetExtension(archivoImagen.FileName);

                    string nombre_imagen = string.Concat(oProducto.IdProducto.ToString(), extension);


                    try
                    {
                        archivoImagen.SaveAs(Path.Combine(ruta_Guardar, nombre_imagen));
                    }
                    catch (Exception ex)
                    {

                        string msg = ex.Message;
                        guardar_imagen_exito = false;
                    }

                    if (guardar_imagen_exito)
                    {
                        oProducto.RutaImagen = ruta_Guardar;
                        oProducto.NombreImagen = nombre_imagen;
                        bool rspta = new CN_Producto().GuardarDatosImagen(oProducto, out mensaje);
                    }

                    else
                    {
                        mensaje = "Se guardo el producto pero hubo problemas con la imagen ";
                    }



                }
            }


            return Json(new { operacion_exitosa = operacion_exitosa,idGenerado = oProducto.IdProducto, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult ImagenProducto(int id)
        {
            bool conversion;
            Producto oproducto = new CN_Producto().Listar().Where(p => p.IdProducto == id).FirstOrDefault();

            string textoBase64 = CN_Recursos.convertirBaase64(Path.Combine(oproducto.RutaImagen, oproducto.NombreImagen),out conversion);


            return Json(new
            {
                conversion = conversion,
                textobase64 = textoBase64,
                extension = Path.GetExtension(oproducto.NombreImagen)

            }, JsonRequestBehavior.AllowGet
            ); 
        }

        [HttpPost]
        public JsonResult EliminarProducto(int id)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Producto().Eliminar(id, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);

        }
        #endregion

    }
}

CapaPresentacionAdmin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

CapaPresentacionAdmin/Views/Mantenedor/Categoria.cshtml
@{
    ViewBag.Title = "Categoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Categorias</li>
</ol>

<div class="card">
    <div class="card-header"> <i class="fa fa-users me-1"></i> Lista de Categorias </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abriModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />
        <table id="tabla" class="display cell-border " style="width:100%">
            <thead>
                <tr>
                    
                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input id="txtid"  nvalue="0" />

                <div class="row  g-1">
                
                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="cbActivo" class="form-label">Activo</label>
                        <select id="cbActivo" class="form-select">

                            <option value="1">Si</option>
                            <option value="0">No</option>

                        </select>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>




    </div>
</div>

@section scripts{
    <script>
        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarCategorias", "Mantenedor")',
                type: "GET",
                dataType: "json",

            },
            columns: [

                {data:'Descripcion'},
                {
                   data:'Activo','render': function(valor){
                        if (valor) {
                            return '<span class="badge bg-success">Si</span>'

                        }
                        else {
                            return '<span class="badge bg-danger">No</span>'
                        }

                    }
                },
                {
                    defaultContent: '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fa fa-pen me-1"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fa fa-trash me-1"></i></button>',
                        'orderable': false,
                        'searchable': false,
                        'width':'90px'

                }
            ],
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.13.4/i18n/es-ES.json'
            },
        });

        function abriModal(json) {
            $("#txtid").val(0);  
            $("#txtDescripcion").val("");
            $("#cbActivo").val(1);

            $("#mensajeError").hide();

            if (json != null) {

                $("#txtid").val(json.IdCategoria);             
                $("#txtDescripcion").val(json.Descripcion);
                $("#cbActivo").val(json.Activo == true ? 1 : 0);

            }

            $("#formModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            abriModal(data);

        })


        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var categoriaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(categoriaSeleccionada).data();


            swal({
                title: "Esta Seguro?",
                text: "Desea eliminar la categoria?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },

                function(){
                    jQuery.ajax({
                       url: '@Url.Action("EliminarCategoria", "Mantenedor")',
                       type:"POST",
                       data: JSON.stringify({ id: data.IdCategoria }),
                       dataType:"json",
                       contentType:"application/json; charset=utf-8",
                        success: function (data) {

                            if (data.resultado) {
                                tabladata.row(categoriaSeleccionada).remove().draw();
                            }else{
                                swal("No se pudo eliminar", data.mensaje,"error")
                            }
                        },
                        error:function(error) {
                            console.log(error)

                        },

                    })

                });

        })

        function Guardar() {

                var Categoria ={
                    IdCategoria: $("#txtid").val(),
                    Descripcion: $("#txtDescripcion").val(),
                    Activo: $("#cbActivo").val() == 1 ? true : false, 
                   

                }

            jQuery.ajax({
                url: '@Url.Action("GuardarCategoria", "Mantenedor")',
                type: "POST",
                data: JSON.stringify({ objeto: Categoria}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // Here we might call the "hide" action 2 times, or simply set the "force" parameter to true:
                    $(".modal-body").LoadingOverlay("hide", true);
                    //Categoria nuevo
                    if (Categoria.IdCategoria == 0) {

                        if (data.resultado != 0) {
                            Categoria.IdCategoria = data.resultado;
                            tabladata.row.add(Categoria).draw(false);
                            $("#formModal").modal("hide");

                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                     //Categoria editar
                    else {
                        if (data.resultado) {
                            tabladata.row(filaSeleccionada).data(Categoria).draw(false);
                            filaSeleccionada = null;
                            $("#formModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {
                    // Here we might call the "hide" action 2 times, or simply set the "force" parameter to true:
                    $(".modal-body").LoadingOverlay("hide", true);
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size:14
                    })

                }
            })




        }

    </script>


}

CapaPresentacionAdmin/Views/Mantenedor/Marcas.cshtml
@{
    ViewBag.Title = "Marcas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="index.html">Mantenimiento</a></li>
    <li class="breadcrumb-item active">Marca</li>
</ol>

<div class="card">
    <div class="card-header"> <i class="fa fa-users me-1"></i> Lista de Marcas </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abriModal(null)">Crear Nuevo</button>
            </div>
        </div>
        <hr />
        <table id="tabla" class="display cell-border " style="width:100%">
            <thead>
                <tr>

                    <th>Descripcion</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Marca</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input id="txtid" nvalue="0" />

                <div class="row  g-1">

                    <div class="col-sm-6">
                        <label for="txtDescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtDescripcion" autocomplete="off">
                    </div>
                    <div class="col-sm-6">
                        <label for="cbActivo" class="form-label">Activo</label>
                        <select id="cbActivo" class="form-select">

                            <option value="1">Si</option>
                            <option value="0">No</option>

                        </select>
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-12">
                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>




    </div>
</div>

@section scripts{
    <script>
        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarMarca", "Mantenedor")',
                type: "GET",
                dataType: "json",

            },
            columns: [

                {data:'Descripcion'},
                {
                   data:'Activo','render': function(valor){
                        if (valor) {
                            return '<span class="badge bg-success">Si</span>'

                        }
                        else {
                            return '<span class="badge bg-danger">No</span>'
                        }

                    }
                },
                {
                    defaultContent: '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fa fa-pen me-1"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fa fa-trash me-1"></i></button>',
                        'orderable': false,
                        'searchable': false,
                        'width':'90px'

                }
            ],
            language: {
                url: 'https://cdn.datatables.net/plug-ins/1.13.4/i18n/es-ES.json'
            },
        });

        function abriModal(json) {
            $("#txtid").val(0);
            $("#txtDescripcion").val("");
            $("#cbActivo").val(1);

            $("#mensajeError").hide();

            if (json != null) {

                $("#txtid").val(json.IdMarca);
                $("#txtDescripcion").val(json.Descripcion);
                $("#cbActivo").val(json.Activo == true ? 1 : 0);

            }

            $("#formModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            abriModal(data);

        })


        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var marcaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(marcaSeleccionada).data();


            swal({
                title: "Esta Seguro?",
                text: "Desea eliminar la Marca?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-danger",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },

                function(){
                    jQuery.ajax({
                       url: '@Url.Action("EliminarMarca", "Mantenedor")',
                       type:"POST",
                       data: JSON.stringify({ id: data.IdMarca }),
                       dataType:"json",
                       contentType:"application/json; charset=utf-8",
                        success: function (data) {

                            if (data.resultado) {
                                tabladata.row(marcaSeleccionada).remove().draw();
                            }else{
                                swal("No se pudo eliminar", data.mensaje,"error")
                            }
                        },
                        error:function(error) {
                            console.log(error)

                        },

                    })

                });

        })

        function Guardar() {

                var Marca ={
                    IdMarca: $("#txtid").val(),
                    Descripcion: $("#txtDescripcion").val(),
                    Activo: $("#cbActivo").val() == 1 ? true : false,


                }

            jQuery.ajax({
                url: '@Url.Action("GuardarMarca", "Mantenedor")',
                type: "POST",
                data: JSON.stringify({ objeto: Marca}),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // Here we might call the "hide" action 2 times, or simply set the "force" parameter to true:
                    $(".modal-body").LoadingOverlay("hide", true);
                    //Categoria nuevo
                    if (Marca.IdMarca == 0) {

                        if (data.resultado != 0) {
                            Marca.IdMarca = data.resultado;
                            tabladata.row.add(Marca).draw(false);
                            $("#formModal").modal("hide");

                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                     //Categoria editar
                    else {
                        if (data.resultado) {
                            tabladata.row(filaSeleccionada).data(Marca).draw(false);
                            filaSeleccionada = null;
                            $("#formModal").modal("hide");
                        }
                        else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
                error: function (error) {
                    // Here we might call the "hide" action 2 times, or simply set the "force" parameter to true:
                    $(".modal-body").LoadingOverlay("hide", true);
                    $("#mensajeError").text("Error Ajax");
                    $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size:14
                    })

                }
            })




        }

    </script>


}